### PR TITLE
Jspm compatibility

### PR DESCRIPTION
**Pull request by wabain**
This PR contains various fixes which makes it easier to use Diva with JavaScript bundlers (particularly JSPM). Much of it is simple, backwards-compatible stuff: adding some configuration, fixing some references to global variables, etc.

The changes which might deserve more attention are:

 1. The build process is changed to wrap all the Diva code in a self-executing function, to make it possible to inject a `require`'d version of jQuery if one is available, instead of relying on jQuery to exist globally.

 2. As a result of 1, some global variables which Diva used to create are now local, specifically `activeDiva` and `activeDivaController` in `utils.js`. As far as I can tell these didn't need to be global, but maybe something @ahwitz wrote relies on them being there?

 3. The `diva` variable used to be tacitly global and is now explicitly assigned to the window object. This could theoretically break some kind of build for someone, but probably won't in practice. (Longer term, variables shouldn't be published globally if they can be exported in a module format.)

PS. The Travis-CI build is broken on develop, so I tested this against the last release on the test-jspm-compatibility branch.

### CODE REVIEW

**Comment by ahwitz** [comment]
The primary use for that object is for when there are multiple Diva objects on a page, keeping track of which was last clicked to delegate events correctly. I'm not sure if @magoni's recent changes made that irrelevant, but if not, it won't work if it's inaccessible. I'd say attach it to the window object until someone tests to see if it's been rendered useless.

**Comment by ahwitz** [comment]
I take that back. It doesn't need to be global, it just needs to be declared.

https://github.com/DDMAL/diva.js/blob/develop/build/js/utils.js#L894 catches if it was the last diva clicked on, and calls

https://github.com/DDMAL/diva.js/blob/develop/build/js/diva.js#L3629 activate(), which sets settings.isActiveDiva to true, which is caught in

https://github.com/DDMAL/diva.js/blob/develop/build/js/diva.js#L1979, which seems to only be looked at on keydown events.

If I understand what I wrote correctly (and the chances of that are slim), the way to test this is to instantiate two Diva objects on the same page with the isActiveDiva stuff commented out, then press the down arrow key to scroll and see if only one moves or if they both move in sync.

I'd recommend replacing that object, regardless, as I wouldn't trust any code I wrote from that long ago at this point.

**Comment by wabain** [comment]
That's more or less what it looked like to me. The changes I made are pretty conservative (except for global access being removed) so that maintenance can probably be left for later.

**Comment by magoni** [comment]
Everything including activeDivaController seem to be working as expected, so this is good to go.

**Pull request merged**
