### PR TITLE
Upgrades to highlight plugin

### PR DESCRIPTION
**Pull request by ahwitz**
I'm pretty sure everything in here is stable and ready to go, since I called the Liber demo ready to go and the changes for this were to match the functionality of the Liber app.

Please check the code and make sure it's okay, formatting- and, if you wish, functionality-wise.

### CODE REVIEW

**Comment by ahwitz** [comment]
And I'll figure out what's making Travis throw a hissy fit soon as well.

**Comment by magoni** [comment]
I ran a `git bisect` and https://github.com/DDMAL/diva.js/commit/f13ff2c059ef3243441b65a2e603516faa086fe8 seems to be the breaking commit. I'll let you look at it because you might have a better idea of what changed.

If you scroll quickly in grid view, the following error appears:
```
TypeError: 'null' is not an object (evaluating 'document.getElementById(settings.ID + 'page-' + pageIndex).appendChild')
```

So it seems there is a problem with the `loadFunction` timeout. However, everything seems fine on `develop`.

**Comment by ahwitz** [comment]
Were you getting the same issue with tests? As of 45163c4, all tests passes on my lab mac, and only the off-by-one ones fail on my Ubuntu machine.

**Comment by ahwitz** [comment]
and with Travis' approval, passing to @magoni for integration into develop

**Pull request merged**
